### ISSUE TITLE
Change links in report for birds and mammals to the PGC site

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#125]
Lower priority, but we should do it.

If we wanted to get fancy, we could have it dynamically switch sites based on the TaxaGroup variable...

**Comment by memoore** [comment]
removed species links since they were not working on any other computer than mine and added taxa links instead.  Inverts other than mussels do not have a link - is there any reference material to link?  

Changed link so that birds and mammals link to PGC SWAP PDF.  

Closing for now, unless we want to reopen the species link mystery.

**Comment by ChristopherTracey** [comment]
That's fine.  This is going to be something that production version of the server can handle.
