### ISSUE TITLE
Cerulean Warbler research and survey needs breaks the tool.

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#222]
Something is not being interpreted correctly by this chunk of LaTeX:

`Cerulean Warbler&\vspace{-\topsep}\begin{itemize}[topsep=0pt]\setlength\itemsep{0em}\item How does management following forestry guidelines affect nest success and survival?\item Assess landscape-level characteristics of cerulean habitat (degree of fragmentation, slope, aspect, elevation, patch size, proximity to water/anthropogenic habitats/gas & oil infrastructure).\end{itemize} & \vspace{-\topsep}\begin{itemize}[topsep=0pt]\setlength\itemsep{0em}\item Conduct off-road point count surveys and spot-mapping for forest interior birds to determine habitat requirements and association with current forest management practices.\item Identify and map areas of high Cerulean Warbler abundance in PA to inform further conservation actions.\end{itemize} \\ `

I think I encountered this error yesterday as well when looking at a site in Frick Park.

**Comment by memoore** [comment]
At quick glance, the ampersand between oil & gas is likely the culprit.



On Mar 8, 2018 2:36 PM, "Christopher Tracey" <notifications@github.com>
wrote:

Something is not being interpreted correctly by this chunk of LaTeX:

Cerulean Warbler&\vspace{-\topsep}\begin{itemize}[topsep=0pt]\setlength\itemsep{0em}\item
How does management following forestry guidelines affect nest success and
survival?\item Assess landscape-level characteristics of cerulean habitat
(degree of fragmentation, slope, aspect, elevation, patch size, proximity
to water/anthropogenic habitats/gas & oil infrastructure).\end{itemize} &
\vspace{-\topsep}\begin{itemize}[topsep=0pt]\setlength\itemsep{0em}\item
Conduct off-road point count surveys and spot-mapping for forest interior
birds to determine habitat requirements and association with current forest
management practices.\item Identify and map areas of high Cerulean Warbler
abundance in PA to inform further conservation actions.\end{itemize} \\

I think I encountered this error yesterday as well when looking at a site
in Frick Park.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/PNHP/COA/issues/222>, or mute the thread

**Comment by ChristopherTracey** [comment]
I think you're right.  You're also on Vacation.

**Comment by ChristopherTracey** [comment]
Found some ampersands in both the survey and research tables.  Updated in the SQLite db--seems to have fixed the problem. Thanks @memoore !!!
