### ISSUE TITLE
Habitat table in metadata

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/COA#55]
Rather than a piecharts (_lots of pie chart hate in this world!_), Cathy and Diana suggested that we have a table of habitats. They also brought up the idea that we should only display macrogroups in the pdf output.

I'm thinking that we should look at two table options. The first would be a simple "% by Macrogroup" and look something like:
![image](https://user-images.githubusercontent.com/8216371/30340929-302b2bfe-97c2-11e7-8f70-b3fbad9e2a0c.png)
For this option, we would have to aggregate the results based on the macrogroup.

The second option could include the habitats something like this:
![image](https://user-images.githubusercontent.com/8216371/30341053-a7edbac6-97c2-11e7-8790-5ff4f53eca2c.png)
This would have all the details on the ecological systems, which might be more informative to some users.

Some of this choice might be related to how we end up displaying the habitats in the species results, but we should probably look at both options.  Or more if you come up with anything brilliant.

**Comment by dyeany** [comment]
My gut reaction is that the habitat information is great to include. However, I think we might want to consider this as a pop-up box or some kind of optional information displayed in the web interface - as you said it may be too much for some users.

From the working group discussions, I think linking species to habitats (i.e. associations) may also be expected. 

Dan has mentioned often that the habitats might be too fine of a classification for the ultimate utility of this tool. I tend to agree, for now. So perhaps sticking with a macrogroup summary with a dropdown feature for habitats could be a solution. Otherwise I'd say just summarize by Macrogroup. Though, I'm not crazy about conifer dominated habitats being buried within these coarser groupings given their significance to many SGCN.

**Comment by ChristopherTracey** [comment]
So, overall we've moved towards the second option and it looks pretty good and effective with some additional table cleanup and formatting (ie. #89).

One cleanup item to do would be to condense the habitats that have modifiers down to a single type.

**Comment by ChristopherTracey** [comment]
I think we're good on this for now.
